FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

## Install php nginx mysql supervisor
RUN apt update && \
    apt install -y php5-fpm php5-cli php5-gd php5-mcrypt php5-mysql php5-curl php-pear php5-dev \
                       nginx \
                       curl \
		       supervisor && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update && \
    apt-get install -y php5-mongo && \
    apt-get install -y autoconf g++ make openssl libssl-dev libcurl4-openssl-dev && \
    apt-get install -y libcurl4-openssl-dev pkg-config && \
    apt-get install -y libsasl2-dev && \
    apt-get install -y libpcre3-dev && \
    pecl install mongo && \
    echo "mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` && \
    pecl install mongodb && \
    echo "extension=mongodb.so" > /etc/php5/cli/conf.d/20-mongo.ini && \
    curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer && \
    apt-get update && \
    apt-get install -y git && \
    apt-get install -y php5-mysqlnd && \
    apt-get install -y vim

## Configuration
RUN sed -i 's/^listen\s*=.*$/listen = \/var\/run\/php5-fpm.sock/' /etc/php5/fpm/pool.d/www.conf && \
	sed -i 's/^pm.max_children\s*=.*$/pm.max_children = 100/' /etc/php5/fpm/pool.d/www.conf && \
	sed -i 's/^pm.start_servers\s*=.*$/pm.start_servers = 15/' /etc/php5/fpm/pool.d/www.conf && \
	sed -i 's/^pm.min_spare_servers\s*=.*$/pm.min_spare_servers = 10/' /etc/php5/fpm/pool.d/www.conf && \
	sed -i 's/^pm.max_spare_servers\s*=.*$/pm.max_spare_servers = 15/' /etc/php5/fpm/pool.d/www.conf && \
	sed -i 's/^pm.max_requests\s*=.*$/pm.max_requests = 200/' /etc/php5/fpm/pool.d/www.conf && \
    sed -i 's/^\;error_log\s*=\s*syslog\s*$/error_log = \/var\/log\/php\/cgi.log/' /etc/php5/fpm/php.ini && \
    sed -i 's/^\;error_log\s*=\s*syslog\s*$/error_log = \/var\/log\/php\/cli.log/' /etc/php5/cli/php.ini

COPY files/root /

WORKDIR /var/www/

VOLUME /var/www/

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]